
server:
  servlet:
    context-path: /api

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    app.seven: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: flexisaf-ses
    couchbase:
      auto-index: true
  main:
    allow-circular-references: true
  mongodb:
    embedded:
      version: 3.2.0

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formate_sql: true
  datasource:
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}
    pool-size: ${env.DATABASE_POOL_SIZE}

jwt-secret: secrete
app:
  memstore:
    host: ${env.REDIS_HOST}
    port: ${env.REDIS_PORT}
    password: ${env.REDIS_PASSWORD}
  email:
    host: ${env.EMAIL_HOST}
    port: ${env.EMAIL_PORT}
    username: ${env.EMAIL_USERNAME}
    password: ${env.EMAIL_PASSWORD}

